### ISSUE TITLE
I'm getting an error when I try to use Mongoose

### ISSUE THREAD

**Issue by leanjunio** [rxdi/xmigrate#22]
```js
// 20210403212944-collections.js
const UserModel = require('../src/models/User');

module.exports = {
  async up () {
    await UserModel.create({ firstName: 'test', lastName: 'owner' });
  },

  async down () {
    return ['Down']
  }
}
```
Output
```
🔥  Status: Operation executed with error
🧨  Error: {"fileName":"20210403215153-add-test-owner.js","migrated":[{"fileName":"20210403212944-collections.js","appliedAt":"2021-04-03T21:56:07.964Z"}]}
📨  Message: Operation `users.insertOne()` buffering timed out after 10000ms
```

I'm not really sure what I'm doing wrong. Does the library only work with MongoClient?

**Comment by Stradivario** [comment]
@leanjunio 

It should work with both MongoClient and Mongoose i am currently using it with Mongoose but also i have some migrations added with native mongodb driver. Lets discuss this one in order to understand what goes wrong. 

I will be available at Telegram https://t.me/dependency you can write me to debug.

**Comment by Stradivario** [comment]
Also i am working on a next version of `xmigrate` where it should be compatible in theory for every database and library.

https://github.com/rxdi/xmigrate/pull/18

This is pull request regarding `hooks` functionality where everyone can choose their preferred way of writing migrations.

**Comment by Stradivario** [comment]
@leanjunio  Can you provide also configuration for `xmigrate.js` ?

**Comment by Stradivario** [comment]
I just found out this topic 
https://stackoverflow.com/questions/65193572/error-message-from-mongodb-operation-disneys-insertone-buffering-timed-out

where some people suggest that they fixed it by adding `srv`  to connection url 
"mongodb+srv://user:password@host/dbname"


Can you please try to do test it out ?

**Comment by Stradivario** [comment]
Closed due to inactivity please re-open if needed.
