### ISSUE TITLE
Not possible to run `xmigrate create` command because of the wrong format, that date-fns won't allow

### ISSUE THREAD

**Issue by serhii-dolia** [rxdi/xmigrate#7]
xmigrate version is 0.7.36
When running a command `node_modules/.bin/xmigrate create "name" --template es6` I get an error: 
```
🔥  Status: Operation executed with error
🧨  Error: {}
📨  Message: Use `yyyy` instead of `YYYY` for formatting years; see: https://git.io/fxCyr
```

The problem is in dist folder(`main.js:14` and `main.js.map`, there we use `YYYYMMDDHH` instead of the small letters), which is not corresponding to the src (there the correct format is used). I wanted to create a PR, but there's no info on how to actually build the dist and I don't have an gapi, so leaving this issue instead.

**Comment by Stradivario** [comment]
@serhii-dolia 

- New version is build
- Bumped to version 0.7.38
- Added change to changelog https://github.com/rxdi/xmigrate/blob/master/CHANGELOG.md
- Introduced with commit https://github.com/rxdi/xmigrate/commit/dc13b962786ffb199aa1c82114d1fb530bf53110


Regards for the issue!
Please try `npm i -g @rxdi/xmigrate` and if you have problem reopen this issue!
